export const products = [
  {
    slug: "sofa-gris",
    name: "Sofá Gris Nórdico",
    price: "$899.999",
    cashPrice: "$719.999",
    priceLabel: "credito",
    image: "/modern-scandinavian-living-room-with-minimalist-fu.jpg",
    category: "sala",
    whatsappMessage: "Sofá Gris Nórdico",
  },
  {
    slug: "sofa-beige",
    name: "Sofá Beige Premium",
    price: "$899.999",
    image: "/scandinavian-minimalist-lounge-chair-in-beige.jpg",
    category: "sala",
    whatsappMessage: "Sofá Beige Premium",
  },
  {
    slug: "mesa-madera",
    name: "Mesa de Madera Pura",
    price: "$499.999",
    cashPrice: "$424.999",
    priceLabel: "transferencia",
    image: "/natural-wood-scandinavian-dining-table.jpg",
    category: "cocina",
    whatsappMessage: "Mesa de Madera Pura",
  },
  {
    slug: "lampara-minimalista",
    name: "Lámpara Minimalista",
    price: "$199.999",
    image: "/modern-minimalist-pendant-light-with-soft-white-de.jpg",
    category: "sala",
    whatsappMessage: "Lámpara Minimalista",
    isLastUnits: true,
  },
  {
    slug: "silla-dining",
    name: "Silla Dining Escandinava",
    price: "$89.999",
    image: "/scandinavian-dining-room-with-wooden-table-and-min.jpg",
    category: "cocina",
    whatsappMessage: "Silla Dining Escandinava",
    isLastUnits: true,
  },
  {
    slug: "mueble-cocina-blanco",
    name: "Mueble Cocina Blanco",
    price: "$599.999",
    cashPrice: "$479.999",
    image: "/scandinavian-white-kitchen-cabinet.jpg",
    category: "cocina",
    whatsappMessage: "Mueble Cocina Blanco",
  },
  {
    slug: "barra-cocina",
    name: "Barra Cocina Minimalista",
    price: "$349.999",
    image: "/scandinavian-minimalist-kitchen-bar.jpg",
    category: "cocina",
    whatsappMessage: "Barra Cocina Minimalista",
  },
  {
    slug: "tablas-madera-cocina",
    name: "Set Tablas de Madera",
    price: "$79.999",
    image: "/scandinavian-wooden-cutting-boards.jpg",
    category: "cocina",
    whatsappMessage: "Set Tablas de Madera",
  },
  {
    slug: "cama-estructura",
    name: "Estructura Cama Nórdica",
    price: "$1.199.999",
    cashPrice: "$1.019.999",
    priceLabel: "transferencia",
    image: "/scandinavian-minimalist-bed-frame-wood.jpg",
    category: "dormitorio",
    whatsappMessage: "Estructura Cama Nórdica",
  },
  {
    slug: "mesita-noche",
    name: "Mesita de Noche",
    price: "$249.999",
    image: "/scandinavian-minimalist-nightstand-wood.jpg",
    category: "dormitorio",
    whatsappMessage: "Mesita de Noche",
    isLastUnits: true,
  },
  {
    slug: "respaldo-cama",
    name: "Respaldo Cama Premium",
    price: "$449.999",
    image: "/scandinavian-minimalist-bed-headboard.jpg",
    category: "dormitorio",
    whatsappMessage: "Respaldo Cama Premium",
  },
  {
    slug: "espejo-dormitorio",
    name: "Espejo de Piso",
    price: "$179.999",
    image: "/scandinavian-minimalist-floor-mirror.jpg",
    category: "dormitorio",
    whatsappMessage: "Espejo de Piso",
  },
  {
    slug: "lampara-dormitorio",
    name: "Lámpara Dormitorio Suave",
    price: "$159.999",
    image: "/scandinavian-minimalist-bedroom-lamp.jpg",
    category: "dormitorio",
    whatsappMessage: "Lámpara Dormitorio Suave",
  },
  {
    slug: "estanteria-blanca",
    name: "Estantería Blanca",
    price: "$549.999",
    cashPrice: "$439.999",
    priceLabel: "oportunidad",
    image: "/scandinavian-minimalist-white-shelving.jpg",
    category: "sala",
    whatsappMessage: "Estantería Blanca",
  },
  {
    slug: "taburete-puff",
    name: "Taburete Puff",
    price: "$199.999",
    image: "/scandinavian-minimalist-puff-ottoman.jpg",
    category: "sala",
    whatsappMessage: "Taburete Puff",
  },
]

export const productDetails: Record<
  string,
  {
    title: string
    price: string
    description: string
    images: string[]
    whatsappMessage: string
  }
> = {
  "sofa-gris": {
    title: "Sofá Gris Nórdico",
    price: "899.999",
    description:
      "Sofá de diseño escandinavo con estructura de madera natural y tapizado en lino gris. Perfecto para crear un ambiente minimalista y acogedor en tu sala. Dimensiones: 200 x 90 x 85 cm. Incluye dos cojines decorativos.",
    images: ["/modern-scandinavian-living-room-with-minimalist-fu.jpg"],
    whatsappMessage: "Sofá Gris Nórdico",
  },
  "sofa-beige": {
    title: "Sofá Beige Premium",
    price: "$899.999",
    description:
      "Sofá premium en beige natural con detalles de madera clara. Ofrece máximo confort y elegancia para tus espacios. Estructura de roble macizo y tapizado en tela orgánica. Dimensiones: 210 x 95 x 88 cm.",
    images: ["/scandinavian-minimalist-lounge-chair-in-beige.jpg"],
    whatsappMessage: "Sofá Beige Premium",
  },
  "mesa-madera": {
    title: "Mesa de Madera Pura",
    price: "$499.999",
    description:
      "Mesa de comedor en madera maciza de roble nórdico. Diseño puro y minimalista que complementa cualquier espacio. Perfecta para reuniones familiares. Dimensiones: 160 x 80 x 75 cm. Materiales naturales de alta calidad.",
    images: ["/natural-wood-scandinavian-dining-table.jpg"],
    whatsappMessage: "Mesa de Madera Pura",
  },
  "lampara-minimalista": {
    title: "Lámpara Minimalista",
    price: "$199.999",
    description:
      "Lámpara colgante de diseño minimalista con estructura de hierro negro y vidrio opal. Iluminación suave y ambiente perfecto para la sala de estar. Compatible con LED. Altura ajustable: 30 - 120 cm.",
    images: ["/modern-minimalist-pendant-light-with-soft-white-de.jpg"],
    whatsappMessage: "Lámpara Minimalista",
  },
  "silla-dining": {
    title: "Silla Dining Escandinava",
    price: "$89.999",
    description:
      "Silla de comedor con diseño escandinavo puro. Estructura de madera maciza y asiento tapizado en lino gris. Ideal para completar tu mesa de comedor. Dimensiones: 50 x 54 x 80 cm. Set de 2 sillas.",
    images: ["/scandinavian-dining-room-with-wooden-table-and-min.jpg"],
    whatsappMessage: "Silla Dining Escandinava",
  },
  "mueble-cocina-blanco": {
    title: "Mueble Cocina Blanco",
    price: "599.999",
    description: "Descripción del Mueble Cocina Blanco",
    images: ["/scandinavian-white-kitchen-cabinet.jpg"],
    whatsappMessage: "Mueble Cocina Blanco",
  },
  "barra-cocina": {
    title: "Barra Cocina Minimalista",
    price: "349.999",
    description: "Descripción de la Barra Cocina Minimalista",
    images: ["/scandinavian-minimalist-kitchen-bar.jpg"],
    whatsappMessage: "Barra Cocina Minimalista",
  },
  "tablas-madera-cocina": {
    title: "Set Tablas de Madera",
    price: "79.999",
    description: "Descripción del Set Tablas de Madera",
    images: ["/scandinavian-wooden-cutting-boards.jpg"],
    whatsappMessage: "Set Tablas de Madera",
  },
  "cama-estructura": {
    title: "Estructura Cama Nórdica",
    price: "1.199.999",
    description: "Descripción de la Estructura Cama Nórdica",
    images: ["/scandinavian-minimalist-bed-frame-wood.jpg"],
    whatsappMessage: "Estructura Cama Nórdica",
  },
  "mesita-noche": {
    title: "Mesita de Noche",
    price: "249.999",
    description: "Descripción de la Mesita de Noche",
    images: ["/scandinavian-minimalist-nightstand-wood.jpg"],
    whatsappMessage: "Mesita de Noche",
  },
  "respaldo-cama": {
    title: "Respaldo Cama Premium",
    price: "449.999",
    description: "Descripción del Respaldo Cama Premium",
    images: ["/scandinavian-minimalist-bed-headboard.jpg"],
    whatsappMessage: "Respaldo Cama Premium",
  },
  "espejo-dormitorio": {
    title: "Espejo de Piso",
    price: "179.999",
    description: "Descripción del Espejo de Piso",
    images: ["/scandinavian-minimalist-floor-mirror.jpg"],
    whatsappMessage: "Espejo de Piso",
  },
  "lampara-dormitorio": {
    title: "Lámpara Dormitorio Suave",
    price: "159.999",
    description: "Descripción de la Lámpara Dormitorio Suave",
    images: ["/scandinavian-minimalist-bedroom-lamp.jpg"],
    whatsappMessage: "Lámpara Dormitorio Suave",
  },
  "estanteria-blanca": {
    title: "Estantería Blanca",
    price: "549.999",
    description: "Descripción de la Estantería Blanca",
    images: ["/scandinavian-minimalist-white-shelving.jpg"],
    whatsappMessage: "Estantería Blanca",
  },
  "taburete-puff": {
    title: "Taburete Puff",
    price: "199.999",
    description: "Descripción del Taburete Puff",
    images: ["/scandinavian-minimalist-puff-ottoman.jpg"],
    whatsappMessage: "Taburete Puff",
  },
}
